<?php

define( 'EASYMEALS_CORE_VERSION', '1.3' );
define( 'EASYMEALS_CORE_ABS_PATH', dirname( __FILE__ ) );
define( 'EASYMEALS_CORE_REL_PATH', dirname( plugin_basename( __FILE__ ) ) );
define( 'EASYMEALS_CORE_URL_PATH', plugin_dir_url( __FILE__ ) );
define( 'EASYMEALS_CORE_ASSETS_PATH', EASYMEALS_CORE_ABS_PATH . '/assets' );
define( 'EASYMEALS_CORE_ASSETS_URL_PATH', EASYMEALS_CORE_URL_PATH . 'assets' );
define( 'EASYMEALS_CORE_INC_PATH', EASYMEALS_CORE_ABS_PATH . '/inc' );
define( 'EASYMEALS_CORE_INC_URL_PATH', EASYMEALS_CORE_URL_PATH . 'inc' );
define( 'EASYMEALS_CORE_CPT_PATH', EASYMEALS_CORE_INC_PATH . '/post-types' );
define( 'EASYMEALS_CORE_CPT_URL_PATH', EASYMEALS_CORE_INC_URL_PATH . '/post-types' );
define( 'EASYMEALS_CORE_SHORTCODES_PATH', EASYMEALS_CORE_INC_PATH . '/shortcodes' );
define( 'EASYMEALS_CORE_SHORTCODES_URL_PATH', EASYMEALS_CORE_INC_URL_PATH . '/shortcodes' );
define( 'EASYMEALS_CORE_PLUGINS_PATH', EASYMEALS_CORE_INC_PATH . '/plugins' );
define( 'EASYMEALS_CORE_PLUGINS_URL_PATH', EASYMEALS_CORE_INC_URL_PATH . '/plugins' );
define( 'EASYMEALS_CORE_HEADER_LAYOUTS_PATH', EASYMEALS_CORE_INC_PATH . '/header/layouts' );
define( 'EASYMEALS_CORE_HEADER_LAYOUTS_URL_PATH', EASYMEALS_CORE_INC_URL_PATH . '/header/layouts' );
define( 'EASYMEALS_CORE_HEADER_ASSETS_PATH', EASYMEALS_CORE_INC_PATH . '/header/assets' );
define( 'EASYMEALS_CORE_HEADER_ASSETS_URL_PATH', EASYMEALS_CORE_INC_URL_PATH . '/header/assets' );

define( 'EASYMEALS_CORE_MENU_NAME', 'easymeals_core_menu' );
define( 'EASYMEALS_CORE_OPTIONS_NAME', 'easymeals_core_options' );

define( 'EASYMEALS_CORE_PROFILE_SLUG', 'mikado' );
